version : '3.8'
services:
    web:
        build: .
        ports:
            - "3000:3000"

        depends_on:
            - db
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - web
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: userpassword
        ports:
            - "3306:3306"
